// HanMark interface-language gate (2.7.0 W9).
//
// 1. The Korean table (src/i18n/ko.ts) and the English table (src/i18n/en.ts) define
//    the same keys with the same {placeholders}; English text is actually translated
//    and every key is used somewhere in src/.
// 2. Korean string literals outside src/i18n are tracked per file against a ratchet
//    baseline (scripts/i18n-baseline.json). A file may not gain Korean literals, and the
//    baseline must be lowered when a file is migrated. Data that is Korean by nature
//    (font names, matched Korean markers) is marked with an `i18n-data` comment on the
//    same line or inside `// i18n-data-begin` ... `// i18n-data-end`.
//
//   node scripts/check-i18n.mjs                    check (part of npm run check)
//   node scripts/check-i18n.mjs --update-baseline  rewrite the baseline after migrating
//   node scripts/check-i18n.mjs --list <file...>   print the Korean literals left in files
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import ts from "typescript";

const ROOT = process.cwd();
const BASELINE_PATH = join(ROOT, "scripts", "i18n-baseline.json");
const HANGUL = /[ᄀ-ᇿ㄰-㆏가-힣]/u;
const PLACEHOLDER = /\{([A-Za-z][A-Za-z0-9_]*)\}/gu;
// Generated byte tables; never shown as interface text.
const GENERATED = new Set(["src/io/embeddedAssets.ts", "src/io/pdfCMapData.ts"]);

const errors = [];
const fail = (message) => errors.push(message);

function toPosix(path) {
  return path.split(sep).join("/");
}

function parse(path) {
  return ts.createSourceFile(path, readFileSync(path, "utf8"), ts.ScriptTarget.ES2022, true, ts.ScriptKind.TS);
}

function literalText(node) {
  if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) return node.text;
  return null;
}

/** Reads `export const <name> ... = { "key": "text" | { one, other } }`. */
function readTable(path, name) {
  const source = parse(path);
  let table = null;
  source.forEachChild((statement) => {
    if (!ts.isVariableStatement(statement)) return;
    for (const declaration of statement.declarationList.declarations) {
      if (!ts.isIdentifier(declaration.name) || declaration.name.text !== name) continue;
      let init = declaration.initializer;
      while (init && (ts.isAsExpression(init) || ts.isSatisfiesExpression(init) || ts.isParenthesizedExpression(init))) {
        init = init.expression;
      }
      if (!init || !ts.isObjectLiteralExpression(init)) {
        fail(`${path}: ${name} must be an object literal`);
        return;
      }
      table = new Map();
      for (const property of init.properties) {
        if (!ts.isPropertyAssignment(property) || !ts.isStringLiteral(property.name)) {
          fail(`${path}: every ${name} entry must be "key": value`);
          continue;
        }
        const key = property.name.text;
        if (table.has(key)) fail(`${path}: duplicate key ${key}`);
        const text = literalText(property.initializer);
        if (text !== null) {
          table.set(key, { kind: "text", forms: [text] });
          continue;
        }
        if (ts.isObjectLiteralExpression(property.initializer)) {
          const forms = {};
          for (const form of property.initializer.properties) {
            const formText = ts.isPropertyAssignment(form) ? literalText(form.initializer) : null;
            const formName = ts.isPropertyAssignment(form) && ts.isIdentifier(form.name) ? form.name.text : "";
            if (formText === null || (formName !== "one" && formName !== "other")) {
              fail(`${path}: ${key} plural forms must be { one: "...", other: "..." }`);
              continue;
            }
            forms[formName] = formText;
          }
          if (typeof forms.one !== "string" || typeof forms.other !== "string") {
            fail(`${path}: ${key} needs both one and other forms`);
            continue;
          }
          table.set(key, { kind: "plural", forms: [forms.one, forms.other] });
          continue;
        }
        fail(`${path}: ${key} must be a single string literal (no concatenation)`);
      }
    }
  });
  if (!table) fail(`${path}: export const ${name} not found`);
  return table ?? new Map();
}

function placeholders(text) {
  return new Set([...text.matchAll(PLACEHOLDER)].map((match) => match[1]));
}

function sameSet(a, b) {
  return a.size === b.size && [...a].every((item) => b.has(item));
}

function withoutParentheses(text) {
  return text.replace(/\([^()]*\)/gu, "");
}

function listSourceFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return listSourceFiles(path);
    return entry.name.endsWith(".ts") ? [path] : [];
  });
}

/** Korean literals outside data markers, per file. */
function scanSource(path) {
  const source = parse(path);
  const lines = source.text.split(/\r?\n/u);
  const dataLines = new Set();
  let inData = false;
  lines.forEach((line, index) => {
    if (line.includes("i18n-data-begin")) inData = true;
    if (inData || /\bi18n-data\b/u.test(line)) dataLines.add(index);
    if (line.includes("i18n-data-end")) inData = false;
  });
  const hits = [];
  const visit = (node) => {
    let text = null;
    if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) text = node.text;
    else if (ts.isTemplateHead(node) || ts.isTemplateMiddle(node) || ts.isTemplateTail(node)) text = node.text;
    if (text !== null && HANGUL.test(text)) {
      const line = source.getLineAndCharacterOfPosition(node.getStart(source)).line;
      if (!dataLines.has(line)) hits.push({ line: line + 1, text });
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return hits;
}

// Migration aid: list what is left in the given files, then stop.
const listIndex = process.argv.indexOf("--list");
if (listIndex >= 0) {
  for (const file of process.argv.slice(listIndex + 1).filter((arg) => !arg.startsWith("--"))) {
    const hits = scanSource(file);
    console.log(`${toPosix(file)}: ${hits.length}`);
    for (const hit of hits) console.log(`  ${hit.line}: ${JSON.stringify(hit.text.slice(0, 120))}`);
  }
  process.exit(0);
}

// 1. Message tables
const ko = readTable("src/i18n/ko.ts", "ko");
const en = readTable("src/i18n/en.ts", "en");
for (const key of ko.keys()) if (!en.has(key)) fail(`en.ts is missing ${key}`);
for (const key of en.keys()) if (!ko.has(key)) fail(`en.ts has a key that ko.ts does not define: ${key}`);
for (const [key, korean] of ko) {
  if (korean.kind !== "text") fail(`ko.ts: ${key} must be a plain string (Korean has no plural forms)`);
  const english = en.get(key);
  if (!english) continue;
  const expected = placeholders(korean.forms[0]);
  if (!korean.forms[0].trim()) fail(`ko.ts: ${key} is empty`);
  english.forms.forEach((form, index) => {
    const actual = placeholders(form);
    const oneForm = english.kind === "plural" && index === 0;
    const comparable = oneForm && !actual.has("count") ? new Set([...actual, "count"]) : actual;
    if (!sameSet(expected, comparable)) {
      fail(`${key}: placeholders differ (ko {${[...expected].join(", ")}} / en {${[...actual].join(", ")}})`);
    }
    if (!form.trim()) fail(`en.ts: ${key} is empty`);
    if (HANGUL.test(withoutParentheses(form))) fail(`en.ts: ${key} contains untranslated Korean text`);
  });
  if (english.kind === "plural" && !expected.has("count")) fail(`${key}: plural forms need a {count} placeholder in ko.ts`);
}

// 2. Korean literals in source files, and key usage
const baseline = JSON.parse(readFileSync(BASELINE_PATH, "utf8"));
const counts = {};
const usedKeys = new Set();
const i18nDir = toPosix(join("src", "i18n"));
for (const file of listSourceFiles("src").map((path) => toPosix(relative(ROOT, path))).sort()) {
  if (file.startsWith(`${i18nDir}/`) || GENERATED.has(file)) continue;
  const text = readFileSync(file, "utf8");
  for (const key of ko.keys()) if (text.includes(`"${key}"`)) usedKeys.add(key);
  const hits = scanSource(file);
  if (hits.length) counts[file] = hits.length;
}
for (const key of ko.keys()) if (!usedKeys.has(key)) fail(`ko.ts: ${key} is not used anywhere in src/`);

if (process.argv.includes("--update-baseline")) {
  const sorted = Object.fromEntries(Object.entries(counts).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(BASELINE_PATH, `${JSON.stringify(sorted, null, 2)}\n`);
  console.log(`Updated ${relative(ROOT, BASELINE_PATH)}: ${Object.keys(sorted).length} files, ${Object.values(sorted).reduce((a, b) => a + b, 0)} Korean literals.`);
} else {
  for (const file of new Set([...Object.keys(baseline), ...Object.keys(counts)])) {
    const now = counts[file] ?? 0;
    const allowed = baseline[file] ?? 0;
    if (now > allowed) {
      const sample = scanSource(file).slice(0, 5).map((hit) => `    ${file}:${hit.line} ${JSON.stringify(hit.text.slice(0, 60))}`);
      fail(`${file}: ${now} Korean literals (baseline ${allowed}). Move interface text to src/i18n or mark data with i18n-data.\n${sample.join("\n")}`);
    } else if (now < allowed) {
      fail(`${file}: ${now} Korean literals, below the baseline ${allowed}. Run node scripts/check-i18n.mjs --update-baseline.`);
    }
  }
}

if (errors.length) {
  console.error(`i18n check failed:\n- ${errors.join("\n- ")}`);
  process.exit(1);
}
const remaining = Object.values(counts).reduce((a, b) => a + b, 0);
console.log(
  `i18n check passed: ${ko.size} keys in Korean and English; ` +
  `${remaining} Korean literals left in ${Object.keys(counts).length} files (baseline).`
);
