import type { App, TFile } from "obsidian";
import { t } from "../i18n";

const HANMARK_SOURCE_KEYS = new Set([
  "hwp-source",
  "hwp-source-cache",
  "hwp-source-format",
  "hwp-source-hash",
  "hwp-source-bytes",
  "hwp-imported-at",
  "hwp-kordoc"
]);

const GENERATED_CALLOUT_TITLE =
  /^>\s*\[!hwp-source\]\s+원본:\s*.+$/i;
const GENERATED_CALLOUT_BODY =
  /^>\s*한글 문서에서 불러온 노트입니다\.\s+\*\*저장\*\*\s+시 원본 서식 그대로 패치되거나\(분기 A\),\s+새 한글 파일이 생성됩니다\(분기 B\/C\)\.\s*$/;

export interface LegacyImportCleanup {
  markdown: string;
  removedFrontmatterKeys: string[];
  removedSourceCallout: boolean;
  changed: boolean;
}

export interface CleanLegacyImportCopy extends LegacyImportCleanup {
  file: TFile;
}

interface FrontmatterRange {
  openingIndex: number;
  closingIndex: number;
  newline: "\n" | "\r\n";
  lines: string[];
}

function leadingFrontmatter(raw: string): FrontmatterRange | null {
  const newline: "\n" | "\r\n" = raw.includes("\r\n") ? "\r\n" : "\n";
  const lines = raw.split(/\r?\n/);
  const first = (lines[0] ?? "").replace(/^\uFEFF/, "");
  if (!/^---[ \t]*$/.test(first)) return null;

  for (let index = 1; index < lines.length; index++) {
    if (/^(?:---|\.\.\.)[ \t]*$/.test(lines[index])) {
      return {
        openingIndex: 0,
        closingIndex: index,
        newline,
        lines
      };
    }
  }

  // Fail closed. HanMark never generated an unclosed YAML block, and editing a
  // malformed user block line-by-line could damage content that only resembles
  // metadata.
  return null;
}

function sourceKey(line: string): string | null {
  if (/^[ \t]/.test(line)) return null;
  const match = line.match(
    /^(?:"([^"]+)"|'([^']+)'|([A-Za-z0-9_-]+))[ \t]*:[ \t]*(.*)$/
  );
  const key = match?.[1] ?? match?.[2] ?? match?.[3] ?? "";
  const value = match?.[4]?.trim() ?? "";
  if (!value || /^[>|][+-]?$/.test(value)) return null;
  return HANMARK_SOURCE_KEYS.has(key) ? key : null;
}

function stripGeneratedFrontmatter(raw: string): {
  markdown: string;
  removedKeys: string[];
  malformed: boolean;
} {
  const frontmatter = leadingFrontmatter(raw);
  const startsFrontmatter =
    /^(?:\uFEFF)?---[ \t]*(?:\r?\n|$)/.test(raw);
  if (!frontmatter) {
    return { markdown: raw, removedKeys: [], malformed: startsFrontmatter };
  }

  const candidates = frontmatter.lines
    .slice(1, frontmatter.closingIndex)
    .map(sourceKey);
  if (
    !candidates.includes("hwp-source") ||
    !candidates.includes("hwp-source-format")
  ) {
    return { markdown: raw, removedKeys: [], malformed: false };
  }
  const removedKeys: string[] = [];
  const kept: string[] = [];
  for (let index = 1; index < frontmatter.closingIndex; index++) {
    const key = sourceKey(frontmatter.lines[index]);
    if (key) {
      removedKeys.push(key);
    } else {
      kept.push(frontmatter.lines[index]);
    }
  }
  if (!removedKeys.length) {
    return { markdown: raw, removedKeys, malformed: false };
  }

  const before = frontmatter.lines[0].startsWith("\uFEFF") ? "\uFEFF" : "";
  const after = frontmatter.lines.slice(frontmatter.closingIndex + 1);
  const hasUserFrontmatter = kept.some((line) => line.trim().length > 0);
  const rebuilt = hasUserFrontmatter
    ? [before + "---", ...kept, frontmatter.lines[frontmatter.closingIndex], ...after]
    : [before + (after.shift() ?? ""), ...after];

  return {
    markdown: rebuilt.join(frontmatter.newline),
    removedKeys: [...new Set(removedKeys)],
    malformed: false
  };
}

function stripGeneratedSourceCallout(raw: string): {
  markdown: string;
  removed: boolean;
} {
  const newline: "\n" | "\r\n" = raw.includes("\r\n") ? "\r\n" : "\n";
  const lines = raw.split(/\r?\n/);
  const output: string[] = [];
  let removed = false;
  let fenceMarker: { character: string; length: number } | null = null;

  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    const fence = line.match(/^\s*(`{3,}|~{3,})/)?.[1] ?? "";
    if (fence) {
      if (!fenceMarker) {
        fenceMarker = { character: fence[0], length: fence.length };
      } else if (
        fence[0] === fenceMarker.character &&
        fence.length >= fenceMarker.length
      ) {
        fenceMarker = null;
      }
      output.push(line);
      continue;
    }

    if (
      !fenceMarker &&
      GENERATED_CALLOUT_TITLE.test(line) &&
      GENERATED_CALLOUT_BODY.test(lines[index + 1] ?? "")
    ) {
      removed = true;
      index++;
      if ((lines[index + 1] ?? "").trim() === "") index++;
      continue;
    }

    output.push(line);
  }

  return {
    markdown: output.join(newline),
    removed
  };
}

/**
 * Remove only metadata and the visible breadcrumb generated by HanMark's
 * legacy importer. User-owned YAML, ordinary callouts, fenced examples, and
 * the editable Markdown body are preserved byte-for-byte wherever possible.
 */
export function stripHanmarkSourceMetadata(raw: string): LegacyImportCleanup {
  const frontmatter = stripGeneratedFrontmatter(raw);
  if (frontmatter.malformed) {
    return {
      markdown: raw,
      removedFrontmatterKeys: [],
      removedSourceCallout: false,
      changed: false
    };
  }
  const callout = stripGeneratedSourceCallout(frontmatter.markdown);
  const changed =
    frontmatter.removedKeys.length > 0 || callout.removed;
  return {
    markdown: callout.markdown,
    removedFrontmatterKeys: frontmatter.removedKeys,
    removedSourceCallout: callout.removed,
    changed
  };
}

/** True when a note contains metadata or a breadcrumb generated by HanMark's legacy importer. */
export function hasHanmarkSourceMetadata(raw: string): boolean {
  return stripHanmarkSourceMetadata(raw).changed;
}

function siblingPath(app: App, source: TFile): string {
  const folder = source.parent?.path;
  const prefix = folder && folder !== "/" ? `${folder}/` : "";
  const stem = t("legacy.copyName", { name: source.basename });
  let path = `${prefix}${stem}.md`;
  let index = 1;
  while (app.vault.getAbstractFileByPath(path)) {
    path = `${prefix}${stem} (${index++}).md`;
  }
  return path;
}

/**
 * Create a non-destructive clean sibling of a note imported by HanMark 2.4.4
 * or earlier. The original note and its source contract remain untouched, so
 * its legacy patch command continues to work.
 */
export async function createCleanLegacyImportCopy(
  app: App,
  source: TFile
): Promise<CleanLegacyImportCopy> {
  const cleanup = stripHanmarkSourceMetadata(await app.vault.read(source));
  if (!cleanup.changed) {
    throw new Error(t("legacy.nothingToClean"));
  }
  const file = await app.vault.create(siblingPath(app, source), cleanup.markdown);
  return { ...cleanup, file };
}
